# https://taskfile.dev
version: '3'

tasks:
  default:
    desc: "List all tasks"
    cmds:
      - task -a

  build:
    desc: "Build the docker image"
    cmds:
      - docker build . -t sgaunet/nginxplorerauth:latest

  tests:
    desc: "Run the tests"
    deps:
      - default
    dir: tests
    cmds:
      - venom run testsuite.yml --output-dir="log" --stop-on-failure

  release:
    desc: "Release the docker image"
    deps:
      - tests
    cmds:
      - bash release.sh
