# https://taskfile.dev
version: '3'

tasks:
  default:
    cmds:
      - docker build . -t sgaunet/nginxplorerauth:latest

  tests:
    deps:
      - default
    dir: tests
    cmds:
      - venom run testsuite.yml --output-dir="log" --stop-on-failure

  release:
    deps:
      - tests
    cmds:
      - bash release.sh
